apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    version: 1
    editable: true
    is_default: true
    
  - name: MySQL
    type: mysql
    url: mysql:3306
    user: admin
    jsonData:
      database: fluentd
    secureJsonData:
      password: admin